modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/desht/ModularRouters/issues"
displayURL="https://minecraft.curseforge.com/projects/modular-routers"
credits=""
authors="desht"
license="MIT"

[[mods]] #mandatory
modId="modularrouters" #mandatory
version="${version}" #mandatory
displayName="Modular Routers"
updateJSONURL="https://raw.githubusercontent.com/desht/ModularRouters/MC1.20.1-master/release_info.json" #optional
description='''
Modular Routers is a highly flexible mod for moving items around the world in various ways.
'''

[[dependencies.modularrouters]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.modularrouters]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
